### ISSUE TITLE
readblock! outputs values in wrong positions

### ISSUE THREAD

**Issue by lazarusA** [meggart/DiskArrays.jl#192]
As of this version, the output of this looks wrong.
using the file from [here](https://drive.google.com/file/d/1Om08vXhgsmLbcGmbEFaachfBHa6Nq5pA/view?usp=sharing)

But, it also happens for other .tif and .nc chunked files.

This looks to happened only when the data is stored into multi chunks, then the reading of those gets corrupted. If is only one, then no issue, or if we use `ds["DQF"].data[1:2000, 1:2000]` is also fine.

***DiskArrays 0.4.4***
```Julia 
using YAXArrays
using NetCDF
using GLMakie

ds = open_dataset("noaa.nc")
heatmap(ds["DQF"])
```
<img width="586" alt="Screenshot 2024-09-15 at 10 56 11" src="https://github.com/user-attachments/assets/80ce7bdf-44bf-4d62-bf12-e44c1df4ae73">

***DiskArrays 0.3.23*** Outputs the correct array

<img width="577" alt="Screenshot 2024-09-15 at 10 46 43" src="https://github.com/user-attachments/assets/16254eac-200f-4369-ada8-d6cff5d086b1">

see also, https://github.com/rafaqz/Rasters.jl/issues/735

**Comment by asinghvi17** [comment]
ooh interesting, thanks Lazaro!  Good to know that it's a DiskArrays thing.

Curious that NetCDF.jl also has the same problem with the `_Unsigned` attribute.

**Comment by asinghvi17** [comment]
This is a more general issue with `collect(diskarray)` then?  Good to know, but a lot of people will use it naively. 

Should collect specifically return what one would expect on a diskarray, instead of looping chunk-wise?

**Comment by rafaqz** [comment]
No `collect` does the right thing. Makie must be actually iterating with `iterate` somewhere. Would be good to find that and switch it to a broadcast

**Comment by asinghvi17** [comment]
Hmm, looks like heatmap's convert_args call `el32convert` which calls `elconvert`.  Have a look at these lines:
https://github.com/MakieOrg/Makie.jl/blob/6dfb420445065c56f5af7944c87ecdfc22eff507/src/conversions.jl#L707C1-L718C4
`elconvert` is calling `map` if it finds an abstract array with missings, or `convert(AbstractArray{NewType}, input)` otherwise.  Either of these might be failing, I'm trying to narrow down where that might be happening.

**Comment by asinghvi17** [comment]
OK, I have a smaller MWE:
```julia
map(identity, parent(ds["DQF"]))
```
gives me a bad heatmap.


[`map(f, A::AbstractArray) = collect_similar(A, Generator(f,A))`](https://github.com/JuliaLang/julia/blob/7c1935d5bf2a7b13008a9494f626febbccd8bf7c/base/abstractarray.jl#L3397) is the implementation that Julia points me to, and I can confirm that that implementation is also problematic.

This is a more general problem, because `map` on a DiskArray may not work like you'd think it would.  Maybe `Base.collect_similar` needs to be adjusted here, so that it iterates in the correct order?

**Comment by rafaqz** [comment]
Shouldn't `DiskGenerator` fix that? Maybe it's not being used somehow. I thought we had fixed this 😅

**Comment by asinghvi17** [comment]
According to `@which` at least, it's not being used...

**Comment by asinghvi17** [comment]
Ah this is https://github.com/meggart/DiskArrays.jl/issues/144 again, I hadn't seen that issue

**Comment by rafaqz** [comment]
Oh right we didn't actually fix that 😭

**Comment by asinghvi17** [comment]
I don't have access to YAXArrays on my current system, but current tests indicate that this is indeed working.
