### ISSUE TITLE
DiskArrays interface for files that are not yet open

### ISSUE THREAD

**Issue by rafaqz** [meggart/DiskArrays.jl#28]
I'm implementing a DiskArrays.jl interface in GeoData.jl. But it doesn't keep files open - they are opened when data is required, and closed again afterwards.

The issue is passing opened files to DiskArrays to apply chunked read/write e.g. during broadcast, and closing the file again afterwards. Using closures or some kind of callback function that runs after all chunks are processed should help here - but I'm not sure exactly where that should go.

**Comment by meggart** [comment]
This is an interesting problem. So far I have experimented with structures that only store the filename as well as the size and element type of the respective disk array, e.g. something like

````
struct UnopenedDiskArray{T,N} <: AbstractDiskArray{T,N}
filename::String
varname::String
size::NTuple{N,Int}
````

and then `readblock!` and `writeblock!` do the full cycle of opening the file, reading the chunk and saving to disk again. In most applications the overhead of opening and closing the files was negligible compared to the actual reading time of a chunk, but that may depend. One advantage of this approach is that it works very nicely in Distributed environments, because you can simply pass this struct to workers and you can do distributed maps over chunks. 

I like the idea of having something that only survives the scope of a broadcast call. Could this be solved by defining `Broadcast.broadcastable` for your types? It would be a bit of an abuse of the interface, but you could define this so that for broadcasting you transform your lazy container into something that holds a pointer to the actual file and is garbage-collected at the end of the operation.

**Comment by rafaqz** [comment]
Nice, your `UnopenedDiskArray` is basically the same as my new `FileArray` in GeoData.jl (which is `<: AbstrackDiskArray`), where `key` is `varname`. I also store the size and chunk size (not sure if chunk size is needed yet):

https://github.com/rafaqz/GeoData.jl/blob/d50930964f6552c62f9855cdcd7bb42f68da2818/src/filearray.jl#L2-L8

And that's what currently happens with `readblock/writeblock!` (although I've got chunking turned of currently). It's probably fine for writing, and does have some nice properties like you describe for distributed workloads, I hadn't really thought of that. Some previous analysis seemed to show that opening/closing files multiple times was slower in some cases, but I probably should investigate that more thoroughly before going further with this, it might be fine just opening them a bunch of times.

I like this way of working because I'm regularly using more than the allowed limits of open files e.g. for hourly multi-year time series. A data-heavy modelling package like GrowthMaps.jl has to iterate over thousands of files, so just passing strings around and opening them for each broadcast operation makes that pretty easy.
