### ISSUE TITLE
Does this strictly have anything to do with Disk? 

### ISSUE THREAD

**Issue by xiaodaigh** [meggart/DiskArrays.jl#40]
Would ChunkCachedArrays.jl be a better name?

**Comment by meggart** [comment]
You are right, it is actually not tied to disks, so a different name would make sense. I am not really happy with having `Cached` in the package name, because it might imply that we do some LRU cache or similar, which we don't...

**Comment by xiaodaigh** [comment]
How about ChunkedArrayInterface.jl? DiskArrays.jl is really misleading.

**Comment by rafaqz** [comment]
Changing the name now means changing the dependencies of quite a few packages. @xiaodaigh you would want to commit to making all the PRs, or this is a headache for the already time-stretched ecosystem for geospatial data.

I'm personally fine with DiskArrays.jl, because its by far the main use case in all the packages that currently depend on it. It also communicates the fact that it's designed around the problem of the source arrays being very slow to load, where ChunkedArrayInterface.jl doesn't.

**Comment by xiaodaigh** [comment]
legitimate real-world concerns.
